<!DOCTYPE HTML>
<!-- NewPage -->
<html lang="it">
<head>
<!-- Generated by javadoc (15) on Sun Sep 19 22:27:30 CEST 2021 -->
<title>wikipediaWebScraperLib Class Hierarchy</title>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8">
<meta name="dc.created" content="2021-09-19">
<meta name="description" content="tree: package: wikipediaWebScraperLib">
<meta name="generator" content="javadoc/PackageTreeWriter">
<link rel="stylesheet" type="text/css" href="../stylesheet.css" title="Style">
<link rel="stylesheet" type="text/css" href="../script-dir/jquery-ui.min.css" title="Style">
<link rel="stylesheet" type="text/css" href="../jquery-ui.overrides.css" title="Style">
<script type="text/javascript" src="../script.js"></script>
<script type="text/javascript" src="../script-dir/jquery-3.5.1.min.js"></script>
<script type="text/javascript" src="../script-dir/jquery-ui.min.js"></script>
</head>
<body class="package-tree-page">
<script type="text/javascript">var pathtoroot = "../";
loadScripts(document, 'script');</script>
<noscript>
<div>JavaScript is disabled on your browser.</div>
</noscript>
<div class="flex-box">
<header role="banner" class="flex-header">
<nav role="navigation">
<!-- ========= START OF TOP NAVBAR ======= -->
<div class="top-nav" id="navbar.top">
<div class="skip-nav"><a href="#skip.navbar.top" title="Skip navigation links">Skip navigation links</a></div>
<ul id="navbar.top.firstrow" class="nav-list" title="Navigation">
<li><a href="../index.html">Overview</a></li>
<li><a href="package-summary.html">Package</a></li>
<li>Class</li>
<li>Use</li>
<li class="nav-bar-cell1-rev">Tree</li>
<li><a href="../deprecated-list.html">Deprecated</a></li>
<li><a href="../index-files/index-1.html">Index</a></li>
<li><a href="../help-doc.html">Help</a></li>
</ul>
</div>
<div class="sub-nav">
<div class="nav-list-search"><label for="search">SEARCH:</label>
<input type="text" id="search" value="search" disabled="disabled">
<input type="reset" id="reset" value="reset" disabled="disabled">
</div>
</div>
<!-- ========= END OF TOP NAVBAR ========= -->
<span class="skip-nav" id="skip.navbar.top">
<!--   -->
</span></nav>
</header>
<div class="flex-content">
<main role="main">
<div class="header">
<h1 class="title">Hierarchy For Package wikipediaWebScraperLib</h1>
<span class="package-hierarchy-label">Package Hierarchies:</span>
<ul class="horizontal">
<li><a href="../overview-tree.html">All Packages</a></li>
</ul>
</div>
<section class="hierarchy">
<h2 title="Class Hierarchy">Class Hierarchy</h2>
<ul>
<li class="circle">java.lang.Object
<ul>
<li class="circle">wikipediaWebScraperLib.<a href="AnalisiInfoWikipedia.html" title="class in wikipediaWebScraperLib"><span class="type-name-link">AnalisiInfoWikipedia</span></a></li>
<li class="circle">wikipediaWebScraperLib.<a href="PaginaWikipediaBuilder.html" title="class in wikipediaWebScraperLib"><span class="type-name-link">PaginaWikipediaBuilder</span></a></li>
<li class="circle">wikipediaWebScraperLib.<a href="ParserSinotticoWikipedia.html" title="class in wikipediaWebScraperLib"><span class="type-name-link">ParserSinotticoWikipedia</span></a> (implements wikipediaWebScraperLib.<a href="ParserTabellaWikipedia.html" title="interface in wikipediaWebScraperLib">ParserTabellaWikipedia</a>)</li>
<li class="circle">wikipediaWebScraperLib.<a href="RigaSinottico.html" title="class in wikipediaWebScraperLib"><span class="type-name-link">RigaSinottico</span></a> (implements java.lang.Iterable&lt;T&gt;, wikipediaWebScraperLib.<a href="RigaTabella.html" title="interface in wikipediaWebScraperLib">RigaTabella</a>)</li>
<li class="circle">wikipediaWebScraperLib.<a href="RigaSinottico.Informazione.html" title="class in wikipediaWebScraperLib"><span class="type-name-link">RigaSinottico.Informazione</span></a></li>
<li class="circle">wikipediaWebScraperLib.<a href="TabellaWikipedia.html" title="class in wikipediaWebScraperLib"><span class="type-name-link">TabellaWikipedia</span></a>&lt;T&gt;
<ul>
<li class="circle">wikipediaWebScraperLib.<a href="Sinottico.html" title="class in wikipediaWebScraperLib"><span class="type-name-link">Sinottico</span></a> (implements java.lang.Iterable&lt;T&gt;)</li>
</ul>
</li>
<li class="circle">java.lang.Throwable (implements java.io.Serializable)
<ul>
<li class="circle">java.lang.Exception
<ul>
<li class="circle">wikipediaWebScraperLib.<a href="RigaNonPresenteException.html" title="class in wikipediaWebScraperLib"><span class="type-name-link">RigaNonPresenteException</span></a></li>
<li class="circle">wikipediaWebScraperLib.<a href="WikipediaUrlErratoException.html" title="class in wikipediaWebScraperLib"><span class="type-name-link">WikipediaUrlErratoException</span></a></li>
</ul>
</li>
</ul>
</li>
<li class="circle">wikipediaWebScraperLib.<a href="WikipediaNavigator.html" title="class in wikipediaWebScraperLib"><span class="type-name-link">WikipediaNavigator</span></a></li>
<li class="circle">wikipediaWebScraperLib.<a href="WikipediaWebPage.html" title="class in wikipediaWebScraperLib"><span class="type-name-link">WikipediaWebPage</span></a>
<ul>
<li class="circle">wikipediaWebScraperLib.<a href="PaginaWikipedia.html" title="class in wikipediaWebScraperLib"><span class="type-name-link">PaginaWikipedia</span></a></li>
</ul>
</li>
</ul>
</li>
</ul>
</section>
<section class="hierarchy">
<h2 title="Interface Hierarchy">Interface Hierarchy</h2>
<ul>
<li class="circle">wikipediaWebScraperLib.<a href="ParserTabellaWikipedia.html" title="interface in wikipediaWebScraperLib"><span class="type-name-link">ParserTabellaWikipedia</span></a></li>
<li class="circle">wikipediaWebScraperLib.<a href="RigaTabella.html" title="interface in wikipediaWebScraperLib"><span class="type-name-link">RigaTabella</span></a></li>
</ul>
</section>
</main>
<footer role="contentinfo">
<nav role="navigation">
<!-- ======= START OF BOTTOM NAVBAR ====== -->
<div class="bottom-nav" id="navbar.bottom">
<div class="skip-nav"><a href="#skip.navbar.bottom" title="Skip navigation links">Skip navigation links</a></div>
<ul id="navbar.bottom.firstrow" class="nav-list" title="Navigation">
<li><a href="../index.html">Overview</a></li>
<li><a href="package-summary.html">Package</a></li>
<li>Class</li>
<li>Use</li>
<li class="nav-bar-cell1-rev">Tree</li>
<li><a href="../deprecated-list.html">Deprecated</a></li>
<li><a href="../index-files/index-1.html">Index</a></li>
<li><a href="../help-doc.html">Help</a></li>
</ul>
</div>
<!-- ======== END OF BOTTOM NAVBAR ======= -->
<span class="skip-nav" id="skip.navbar.bottom">
<!--   -->
</span></nav>
</footer>
</div>
</div>
</body>
</html>
