package wikipediaWebScraperLib;

/**
 * Classe di test per controllo sinottico. La parte di codice html è stata copiata dalla relativa pagina
 * Wikipedia.
 * La classe PaginaWikipediaBuildeEInfoWikipediaTester effettua altri test sulla classe del Parser
 * aggiungendo casi nulli.
 * 
 * * @author Ian Tirso Cini
 *
 */
public class TesterParserSinotticoWikipedia {
	
	public static void main(String args[]) {
		ParserSinotticoWikipedia psw = new ParserSinotticoWikipedia();
		
		String sinottico = "<table class=\"sinottico\" summary=\"Tabella sinottica che riassume i principali dati del monarca o aristocratico\">\r\n"
				+ "\r\n"
				+ "<tbody><tr class=\"sinottico_testata\">\r\n"
				+ "<th colspan=\"2\" class=\"sinottico_testata\" style=\"color:white; background:#B80049;\">Tolomeo XV<br />(Tolomeo Filopatore Filometore Cesare)\r\n"
				+ "</th></tr>\r\n"
				+ "\r\n"
				+ "<tr>\r\n"
				+ "<td colspan=\"2\" style=\"text-align:center;\"><div class=\"center\"><div class=\"floatnone\"><a href=\"/wiki/File:Caesarion.jpg\" class=\"image\"><img alt=\"Caesarion.jpg\" src=\"//upload.wikimedia.org/wikipedia/commons/thumb/1/1a/Caesarion.jpg/260px-Caesarion.jpg\" decoding=\"async\" width=\"260\" height=\"285\" srcset=\"//upload.wikimedia.org/wikipedia/commons/thumb/1/1a/Caesarion.jpg/390px-Caesarion.jpg 1.5x, //upload.wikimedia.org/wikipedia/commons/thumb/1/1a/Caesarion.jpg/520px-Caesarion.jpg 2x\" data-file-width=\"934\" data-file-height=\"1024\" /></a></div></div><a href=\"/wiki/Tolomeo_XV_Cesare_in_granodiorite_(SCA_88)\" title=\"Tolomeo XV Cesare in granodiorite (SCA 88)\">Testa colossale di Tolomeo XV Cesare</a> (<a href=\"/wiki/Bibliotheca_Alexandrina\" title=\"Bibliotheca Alexandrina\">Bibliotheca Alexandrina</a>, <a href=\"/wiki/Alessandria_d%27Egitto\" title=\"Alessandria d&#39;Egitto\">Alessandria d'Egitto</a>)\r\n"
				+ "</td></tr>\r\n"
				+ "\r\n"
				+ "<tr class=\"sinottico_divisione\">\r\n"
				+ "<th colspan=\"2\" style=\"background-color:#CCF;\"><a href=\"/wiki/Faraone\" title=\"Faraone\">Signore d'Egitto</a>\r\n"
				+ "</th></tr>\r\n"
				+ "<tr>\r\n"
				+ "<td colspan=\"2\" align=\"center\"><div class=\"center\"><div class=\"floatnone\"><a href=\"/wiki/File:Double_crown.svg\" class=\"image\" title=\"Stemma\"><img alt=\"Stemma\" src=\"//upload.wikimedia.org/wikipedia/commons/thumb/0/06/Double_crown.svg/75px-Double_crown.svg.png\" decoding=\"async\" width=\"75\" height=\"100\" srcset=\"//upload.wikimedia.org/wikipedia/commons/thumb/0/06/Double_crown.svg/112px-Double_crown.svg.png 1.5x, //upload.wikimedia.org/wikipedia/commons/thumb/0/06/Double_crown.svg/150px-Double_crown.svg.png 2x\" data-file-width=\"375\" data-file-height=\"500\" /></a></div></div>\r\n"
				+ "</td></tr>\r\n"
				+ "<tr>\r\n"
				+ "<th>In carica\r\n"
				+ "</th>\r\n"
				+ "<td><a href=\"/wiki/44_a.C.\" title=\"44 a.C.\">44</a> – <a href=\"/wiki/30_a.C.\" title=\"30 a.C.\">30 a.C.</a><br /><small>(con <a href=\"/wiki/Cleopatra\" title=\"Cleopatra\">Cleopatra</a>)</small>\r\n"
				+ "</td></tr>\r\n"
				+ "\r\n"
				+ "\r\n"
				+ "\r\n"
				+ "\r\n"
				+ "<tr>\r\n"
				+ "<th>Predecessore\r\n"
				+ "</th>\r\n"
				+ "<td><a href=\"/wiki/Tolomeo_XIV\" title=\"Tolomeo XIV\">Tolomeo XIV</a> e <a href=\"/wiki/Cleopatra\" title=\"Cleopatra\">Cleopatra</a>\r\n"
				+ "</td></tr>\r\n"
				+ "\r\n"
				+ "\r\n"
				+ "<tr>\r\n"
				+ "<th>Successore\r\n"
				+ "</th>\r\n"
				+ "<td><i>nessuno</i><br />(annessione alla <a href=\"/wiki/Repubblica_romana\" title=\"Repubblica romana\">Repubblica romana</a>)\r\n"
				+ "</td></tr>\r\n"
				+ "\r\n"
				+ "\r\n"
				+ "\r\n"
				+ "\r\n"
				+ "\r\n"
				+ "\r\n"
				+ "<tr>\r\n"
				+ "<th colspan=\"2\" style=\"background:#CCF; height:3px\">\r\n"
				+ "</th></tr>\r\n"
				+ "<tr>\r\n"
				+ "<th>Nome completo\r\n"
				+ "</th>\r\n"
				+ "<td>Πτολεμαῖος Φιλοπάτωρ Φιλομήτωρ Καῖσαρ (<i>Ptolemàios Philopàtōr Philomḕtōr Kàisar</i>)<br /><small>(per la titolatura egizia, vedi la <a href=\"#Titolatura\">sezione dedicata</a>)</small>\r\n"
				+ "</td></tr>\r\n"
				+ "\r\n"
				+ "\r\n"
				+ "\r\n"
				+ "\r\n"
				+ "\r\n"
				+ "\r\n"
				+ "\r\n"
				+ "\r\n"
				+ "<tr>\r\n"
				+ "<th>Altri titoli\r\n"
				+ "</th>\r\n"
				+ "<td><a href=\"/wiki/Re_dei_Re\" title=\"Re dei Re\">Re dei Re</a>\r\n"
				+ "</td></tr>\r\n"
				+ "<tr>\r\n"
				+ "<th>Nascita\r\n"
				+ "</th>\r\n"
				+ "<td><a href=\"/wiki/47_a.C.\" title=\"47 a.C.\">47 a.C.</a>\r\n"
				+ "</td></tr>\r\n"
				+ "<tr>\r\n"
				+ "<th>Morte\r\n"
				+ "</th>\r\n"
				+ "<td>agosto <a href=\"/wiki/30_a.C.\" title=\"30 a.C.\">30 a.C.</a>\r\n"
				+ "</td></tr>\r\n"
				+ "\r\n"
				+ "\r\n"
				+ "\r\n"
				+ "\r\n"
				+ "\r\n"
				+ "\r\n"
				+ "<tr>\r\n"
				+ "<th>Dinastia\r\n"
				+ "</th>\r\n"
				+ "<td><a href=\"/wiki/Dinastia_tolemaica\" title=\"Dinastia tolemaica\">Tolomei</a> e <a href=\"/wiki/Dinastia_giulio-claudia\" title=\"Dinastia giulio-claudia\">giulio-claudia</a>\r\n"
				+ "</td></tr>\r\n"
				+ "<tr>\r\n"
				+ "<th>Padre\r\n"
				+ "</th>\r\n"
				+ "<td><a href=\"/wiki/Gaio_Giulio_Cesare\" title=\"Gaio Giulio Cesare\">Gaio Giulio Cesare</a>\r\n"
				+ "</td></tr>\r\n"
				+ "<tr>\r\n"
				+ "<th>Madre\r\n"
				+ "</th>\r\n"
				+ "<td><a href=\"/wiki/Cleopatra\" title=\"Cleopatra\">Cleopatra</a>\r\n"
				+ "</td></tr>\r\n"
				+ "\r\n"
				+ "\r\n"
				+ "\r\n"
				+ "\r\n"
				+ "\r\n"
				+ "\r\n"
				+ "\r\n"
				+ "\r\n"
				+ "\r\n"
				+ "\r\n"
				+ "\r\n"
				+ "\r\n"
				+ "\r\n"
				+ "\r\n"
				+ "\r\n"
				+ "\r\n"
				+ "\r\n"
				+ "</tbody></table>";

		Sinottico sin = psw.analizzaTabella(sinottico);
		for (RigaSinottico riga : sin) {
			System.out.println(riga);
		}
	}
}
